services:
  prefect:
    build: .
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - GIZMOSQL_URL=${GIZMOSQL_URL}
      - GIZMOSQL_USERNAME=${GIZMOSQL_USERNAME}
      - GIZMOSQL_PASSWORD=${GIZMOSQL_PASSWORD}
      - TUYA_DEVICE_ID=${TUYA_DEVICE_ID}
      - TUYA_DEVICE_IP=${TUYA_DEVICE_IP}
      - TUYA_DEVICE_KEY=${TUYA_DEVICE_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - OILPRICE_API_KEY=${OILPRICE_API_KEY}
      - FRED_API_KEY=${FRED_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LARANJEIRA_MATRIX_TOKEN=${LARANJEIRA_MATRIX_TOKEN}
      - LARANJEIRA_MATRIX_HOMESERVER=${LARANJEIRA_MATRIX_HOMESERVER}
      - LARANJEIRA_MATRIX_ROOM_ID=${LARANJEIRA_MATRIX_ROOM_ID}
    ports:
      - "4200:4200"
    volumes:
      - ./data:/root/.prefect
      - pgdata-prefect:/var/lib/postgresql/data
      - ./flows:/app/flows
      - ./secrets:/app/secrets
      - ./prefect.yaml:/app/prefect.yaml:rw
    restart: unless-stopped

volumes:
  pgdata-prefect:
